name: Production CD
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build image
      run: make build
    - name: Push image with commit sha
      run: make docker-push TAG=$(git rev-parse --short "$GITHUB_SHA")
    - name: Push image with latest tag
      run: make docker-push TAG=latest
  deploy:
    needs: build
    name: Rollout deployment
    runs-on: ubuntu-latest
    steps:
      - name: Rollout deployment
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            kubectl rollout restart deployment dsa-frontend -n dsa
